name: ms-mint
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - lxml
  - numpy
  - matplotlib
  - pandas
  - pandoc
  - pip
  - plotly
  - plotly_express
  - dash
  - dash-bootstrap-components
  - pyqt
  - python=3.7.2
  - scipy
  - setuptools
  - sqlite
  - statsmodels
  - pip:
    - openpyxl==2.6.0
    - pyteomics==4.0.1
    - colorlover

